### ISSUE TITLE
Bug: `spacetime logs -f` doesn't show you the latest

### ISSUE THREAD

**Issue by coolreader18** [clockworklabs/SpacetimeDB#1217] opened 2024-05-13 14:53 UTC

**Comment by coolreader18** [comment] 2024-05-13 14:55
Unable to reproduce - cc @cloutiertyler @jdetter

**Comment by cloutiertyler** [comment] 2024-05-13 18:06
Noa told me today that they could not repro

**Comment by jdetter** [comment] 2024-10-07 18:00
Today this was reproduced using BitCraft and wasted quite a lot of the SpacetimeDB team's time and the BitCraft team's time. This issue exists in 0.11.1 and we must make sure this either has been fixed in 0.12.0 or will be fixed in 1.0.

**Comment by kurtismullins** [comment] 2024-10-07 18:45
> There may be some confouding factors here.

Just to add, SpacetimeDB was running within a Docker container on the remote machine.

**Comment by bfops** [comment] 2024-10-08 17:51
@kurtismullins @jdetter is the repro that you run `spacetime logs -f` and it immediately doesn't show the latest, or that new logs don't always show up?

**Comment by coolreader18** [comment] 2024-11-12 18:54
From John on Oct 7:
> The solution here was the there was no bug on the spacetimedb side, this is a known bug in the CLI which seems to still exist in 0.11.1 which we must fix for 1.0. Essentially `spacetime logs -f <module-name>` for some reason does not fully display the bottom of the log and it does not print new logs. You can see the entire log by doing something like `spacetime logs -f <module-name> 100000`.

**Comment by bfops** [comment] 2024-11-13 02:19
> From John on Oct 7:
> 
> > The solution here was the there was no bug on the spacetimedb side, this is a known bug in the CLI which seems to still exist in 0.11.1 which we must fix for 1.0. Essentially `spacetime logs -f <module-name>` for some reason does not fully display the bottom of the log and it does not print new logs. You can see the entire log by doing something like `spacetime logs -f <module-name> 100000`.

Super helpful, thank you!

**Comment by gefjon** [comment] 2024-11-22 18:41
Closing as could not reproduce.

**Closed by gefjon** 2024-11-22 18:41 UTC
