### ISSUE TITLE
Getting a new identity every time I spacetime publish/call 

### ISSUE THREAD

**Issue by jdetter** [clockworklabs/SpacetimeDB#333] opened 2023-09-27 16:28 UTC
![image](https://github.com/clockworklabs/SpacetimeDB/assets/4099508/af58d0c0-066d-41e3-a415-b30e76b2d45c)

**Comment by jdetter** [comment] 2023-10-26 16:52
I randomly get into this state from time to time, next time it happens I'll dump my config here

**Comment by kim** [comment] 2024-04-18 08:01
I can reproduce this by not having a `default_identity` for a server. Which I think I don't have because `server add` doesn't set it.

**Comment by kim** [comment] 2024-04-18 08:03
Sometimes it seems the fresh identity is then set as the default, but sometimes not.

Maybe we should just prompt to select an identity if it wasn't set as a default nor an argument?

**Comment by gefjon** [comment] 2024-06-11 16:37
I suspect this is fixed by #1109 , #1196 and #1341 . Closing, but if it reappears we can reopen.

**Closed by gefjon** 2024-06-11 16:37 UTC
Labels: bug
